### PR TITLE
Removed archiver and replaced with native golang

### PR DESCRIPTION
**Pull request by dgannon991**
We use magex in porter (https://github.com/getporter/porter) and recently we've had a few high severity warnings relating to the use or archiver. 

First I attempted to use their replacement package (archives) but found it still had a vast number of vulnerabilities reported by RHDA. Here I've gone with a simple native golang implementation, so hopefully that keeps the numbers down in the future!

This delivers towards getporter/porter#3282

### CODE REVIEW

**Comment by cpanato** [comment]
thanks i will try to review over the weekend or next week

also can we add tests?

**Comment by dgannon991** [comment]
That's ace, thank you!

**Review by cpanato — APPROVED** [review]
cool
seems ok to me

thanks!

**Comment by dgannon90** [comment]
Oh brilliant, thank you! Do you know if/when you plan to cut a new release, just so I can keep porter up to date with the changes? Cheers!

**Comment by dgannon991** [comment]
Oh brilliant, thank you! Do you know if/when you plan to cut a new release, just so I can keep porter up to date with the changes? Cheers!

**Comment by cpanato** [comment]
maybe next week, need to check other things before, but while that you can point to the main branch your go.mod and run tests :)

**Comment by dgannon991** [comment]
Oh brilliant, thanks for the confirm. Yup, I have our repos pointing at the commit and all tests are passing, so we're looking good :)

**Comment by cpanato** [comment]
@dgannon991 released: https://github.com/uwu-tools/magex/releases/tag/v0.10.1

**Comment by justaugustus** [comment]
This was on the backlog for me, so thanks for the contribution, @dgannon991!
...and the release, @cpanato!

**Comment by dgannon991** [comment]
No worries at all, always happy to help :) Thank you both!

**Pull request merged**
